services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: always
    network_mode: "host" # For connecting to Ankiconnect on the host